### ISSUE TITLE
[Bug] All Links : when clicking on link "History Links" and "Folder Links" selection buttons get duplicated

### ISSUE THREAD

**Issue by linky3754** [LinkoraApp/Linkora#90]
**Describe the bug**

-> when clicking on link in "All Links" section, "History Links" and "Folder Links" selection buttons get duplicated

**To Reproduce**

1. Go to All Links 
2. Choose sort by Newest to Oldest
3. At top notice there are two selection buttons : "History Links" and "Folder Links"
4. Open link. At this point you will be navigated to your browser (i.e. out of LinkoraApp)
5. Press back button. At this point you will be back in LinkoraApp
6. You should see each of "History Links" and "Folder Links" show twice, rather than once as originally shown

**Expected behavior**

-> Expect "History Links" and "Folder Links" only to be shown once

**Screenshots**

![Image](https://github.com/user-attachments/assets/a3033c22-c4a9-42cd-8b9b-ea5bba364963)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6
 - OS: Android 15

**Comment by sakethpathike** [comment]
fixed in the latest release: https://github.com/LinkoraApp/Linkora/releases/tag/release-v0.13.2

**Comment by linky3754** [comment]
Hi @sakethpathike thanks for fix. I am on version 0.13.6 and I still see this happening. Do you also see it on your end? Thanks

**Comment by sakethpathike** [comment]
> I still see this happening

> I also find the same thing happens in Search dialog box (when I search for bookmarks containing a word)

hmmm, that's weird. I'll look into it

> Do you also see it on your end?

nope

**Comment by linky3754** [comment]
So it seems when I open via Share Menu the above does not happen. It only happens when I click on the link and it automatically opens in browser (i.e. not using share menu).

To be honest I can live with this (it might be specific to my device).
